// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgrzlhduzadkiafamxhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncnpsaGR1emFka2lhZmFteGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjE1MzYsImV4cCI6MjA3MjczNzUzNn0.uzQRvbbF30wrPC4hwjANKfFhstOstdEL6W0gup98R4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});